name: CI

on: [ push, pull_request ]

env:
  LTSMIN_VERSION: v3.1.0
  LTSMIN_REPO: Meijuh

jobs:
  tests-and-analysis:
    name: "Tests and Analysis (JDK: ${{ matrix.jdk }})"
    strategy:
      matrix:
        jdk: [ 1.8, 11 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: |
            ~/ltsmin
            ~/.m2
            !~/.m2/repository/net/automatalib
            !~/.m2/repository/de/learnlib
          key: cache-tests-and-analysis-${{ matrix.jdk }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: cache-tests-and-analysis-${{ matrix.jdk }}-
      - name: Set up GraphViz
        run: |
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y graphviz
      - name: Set up LTSmin
        shell: bash
        run: |
          $GITHUB_WORKSPACE/.github/install-ltsmin.sh
          echo "$HOME/ltsmin/${{ env.LTSMIN_VERSION }}/bin" >> $GITHUB_PATH
      - name: Download Maven
        if: ${{ env.ACT }}
        run: |
          curl -sL https://www-eu.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip -o maven.zip
          apt-get update
          apt-get -y install unzip
          unzip -d /usr/share maven.zip
          rm maven.zip
          ln -s /usr/share/apache-maven-3.6.3/bin/mvn /usr/bin/mvn
          echo "M2_HOME=/usr/share/apache-maven-3.6.3" | tee -a /etc/environment
      - name: Set up AutomataLib
        shell: bash
        # Set environment variables "AUTOMATALIB_FORK" and "AUTOMATALIB_BRANCH" to build custom AutomataLib versions.
        # Defaults are "LearnLib" and the current/targeted LearnLib branch ($GITHUB_REF, relies on the same naming
        # conventions between AutomataLib and LearnLib branches).
        run: |
          git clone -b ${AUTOMATALIB_BRANCH:-${GITHUB_REF#refs/*/}} --single-branch https://github.com/${AUTOMATALIB_FORK:-LearnLib}/automatalib.git ${HOME}/automatalib-git
          cd ${HOME}/automatalib-git
          mvn -B install -DskipTests
          cd $GITHUB_WORKSPACE
      - name: Run Maven
        run: mvn -B install site -Pintegration-tests,code-analysis,bundles
  platform-integration:
    name: "Platform Integration (JDK: ${{ matrix.jdk }}, OS: ${{ matrix.os }})"
    needs: [ tests-and-analysis ]
    strategy:
      matrix:
        jdk: [ 1.8, 11 ]
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2
            !~/.m2/repository/net/automatalib
            !~/.m2/repository/de/learnlib
          key: cache-platform-integration-${{ matrix.jdk }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: cache-platform-integration-${{ matrix.jdk }}-
      - name: Set up AutomataLib
        shell: bash
        # Set environment variables "AUTOMATALIB_FORK" and "AUTOMATALIB_BRANCH" to build custom AutomataLib versions.
        # Defaults are "LearnLib" and the current/targeted LearnLib branch ($GITHUB_REF, relies on the same naming
        # conventions between AutomataLib and LearnLib branches).
        run: |
          git clone -b ${AUTOMATALIB_BRANCH:-${GITHUB_REF#refs/*/}} --single-branch https://github.com/${AUTOMATALIB_FORK:-LearnLib}/automatalib.git ${HOME}/automatalib-git
          cd ${HOME}/automatalib-git
          mvn -B install -DskipTests
          cd $GITHUB_WORKSPACE
      - name: Run Maven
        run: mvn -B '-Dmaven.compiler.source=${{ matrix.jdk }}' '-Dmaven.compiler.target=${{ matrix.jdk }}' install
